### ISSUE TITLE
Not able to understand what needs to be in config for real firebase project

### ISSUE THREAD

**Issue by santoshv98** [Code-Hex/firebase-auth-cloudflare-workers#9]
Great job with the library, impressive

1. Can you give an example of what needs to be really mentioned in the config ? When we setup firebase app and pull out the json , we have "apiKey", "authDomain", projectId (this is clear), "appId" and "measurementId". Not really understanding what among these need to go into wrangler.toml.  In your example, you mentioned previewId and Id. What would they map to?
2. How does it determine if I don't intend to run an emulator? Just leave out FIREBASE_AUTH_EMULATOR_HOST to empty string?
3. If I have a worker to run on multiple firebase projects, how do I handle this scenario?

One specific example with a firebase project would be really helpful

**Comment by Code-Hex** [comment]
@santoshv98 Thanks!

1. I put [example](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/tree/main/example) directory you may know. only required `projectId`.
2. This library determines that you are not using an emulator if `FIREBASE_AUTH_EMULATOR_HOST` is empty or undefined. code is [here](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/1883637a32e7ced1a6d6795275e5cd068ecd77ee/src/emulator.ts#L6).
3. I'm sorry. I can't answer because I don't know what kind of scenario you are using multiple projects in the first place. But You might need 3 workers because JWT validation is different for each project.
